<?php

namespace examen\chantierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * chantierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class chantierRepository extends EntityRepository
{
}
