<?php

namespace examen\chantierBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ouvrierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ouvrierRepository extends EntityRepository
{

    
         public function findBychantier($chantier) {
             $qb=$this->createQueryBuilder('p');
            $qb->where('p.chantier=:chantier')
                   
                    ->setParameter('chantier', $chantier);
                  
            return $qb->getQuery()->getResult();
    }
}
